version: "3.8"
services:
  redis:
    image: redis:latest
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS__HOST}
      VOLUMES_DIR: ~/{VOLUMES_DIR}
    ports:
      - ${REDIS__PORT}:${REDIS__PORT}
    volumes:
      - ~/${VOLUMES_DIR}/redis-config:/usr/local/etc/redis/redis.conf
      - ~/${VOLUMES_DIR}/redis-data:/data
    command: "redis-server /usr/local/etc/redis/redis.conf"
    restart: "unless-stopped"

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${TG_BOT__PORT}:${TG_BOT__PORT}
    volumes:
      - .:/bachaterio_bot
    stop_signal: SIGINT
    restart: "unless-stopped"

  mongo:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
    ports:
      - ${MONGO__PORT}:${MONGO__PORT}
    volumes:
      - ~/${VOLUMES_DIR}/mongo-data/:/data/db

